"""initial

Revision ID: 163b3ad3d39a
Revises: 
Create Date: 2026-04-05 03:21:21.995188

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '163b3ad3d39a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column(
        'source',
        sa.Enum('hn', 'rss', 'reddit', 'twitter', 'youtube', name='source_enum'),
        nullable=False,
    ),
    sa.Column('source_id', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('authenticity_score', sa.Float(), nullable=True),
    sa.Column('calmness_score', sa.Float(), nullable=True),
    sa.Column(
        'content_type',
        sa.Enum('article', 'thread', 'video', 'post', 'comment', name='content_type_enum'),
        nullable=True,
    ),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_content_source_source_id')
    )
    op.create_index('ix_content_items_ingested_at', 'content_items', ['ingested_at'], unique=False)
    op.create_index(
        'ix_content_items_published_at', 'content_items', ['published_at'], unique=False,
    )
    op.create_index(
        'ix_content_items_quality_score', 'content_items', ['quality_score'], unique=False,
    )
    op.create_index('ix_content_items_source', 'content_items', ['source'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column(
        'delivery_time', sa.String(length=5), nullable=True,
        comment="HH:MM in UTC, e.g. '08:00'",
    ),
    sa.Column('magic_link_token', sa.String(length=512), nullable=True),
    sa.Column('magic_link_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_magic_link_token', 'users', ['magic_link_token'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('click', 'open', 'dismiss', name='action_enum'), nullable=False),
    sa.Column(
        'source_surface',
        sa.Enum('email', 'web', name='source_surface_enum'),
        nullable=False,
    ),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interactions_content_id', 'interactions', ['content_id'], unique=False)
    op.create_index('ix_interactions_timestamp', 'interactions', ['timestamp'], unique=False)
    op.create_index(
        'ix_interactions_user_content', 'interactions',
        ['user_id', 'content_id'], unique=False,
    )
    op.create_index('ix_interactions_user_id', 'interactions', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_token', 'sessions', ['token'], unique=True)
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_index('ix_sessions_token', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_interactions_user_id', table_name='interactions')
    op.drop_index('ix_interactions_user_content', table_name='interactions')
    op.drop_index('ix_interactions_timestamp', table_name='interactions')
    op.drop_index('ix_interactions_content_id', table_name='interactions')
    op.drop_table('interactions')
    op.drop_index('ix_users_magic_link_token', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_content_items_source', table_name='content_items')
    op.drop_index('ix_content_items_quality_score', table_name='content_items')
    op.drop_index('ix_content_items_published_at', table_name='content_items')
    op.drop_index('ix_content_items_ingested_at', table_name='content_items')
    op.drop_table('content_items')
    # ### end Alembic commands ###
